### ISSUE TITLE
Font influences search bar position

### ISSUE THREAD

**Issue by JacobValdemar** [RoadieHQ/backstage-plugin-github-pull-requests#11]
![Screenshot_2020-09-28 release-manager-bot Pull requests plugin Backstage(1)](https://user-images.githubusercontent.com/16527874/94420505-8b575780-0184-11eb-9420-b252449fc98d.png)
![Screenshot_2020-09-28 release-manager-bot Pull requests plugin Backstage(2)](https://user-images.githubusercontent.com/16527874/94421392-c312cf00-0185-11eb-92c8-f5391809eb80.png)

First of all, thank you so much for creating this plugin and making it open source!

As you can see in the picture I stumbled into an issue when using the plugin while I has configured backstage to use another font (Poppins). 

So steps to reproduce:
- Follow this guide https://backstage.io/docs/getting-started/app-custom-theme
- Add and configure plugin-github-pull-requests

**Comment by dtuite** [comment]
Hey Jacob. Thanks for opening this issue. We will take a look and see what we can do about this.

**Comment by iain-b** [comment]
Someone reached out to me about a hacktoberfest contribution and I think this might be appropriate. Could I "reserve" this for them until Monday at least?

**Comment by dtuite** [comment]
@iain-b great idea. Thanks

**Comment by JacobValdemar** [comment]
I'm not up-to-date with what hacktoberfest is, but it seems we're in November now, so maybe this will not be fixed in hacktoberfest 🙂

**Comment by JacobValdemar** [comment]
@Irma12 The issue has been resolved :)
