### ISSUE TITLE
Pull request statistics calculation on small repos are broken

### ISSUE THREAD

**Issue by adamdmharvey** [RoadieHQ/backstage-plugin-github-pull-requests#26]
When viewing pull request statistics on a very small repo, the mathematic calculations don't fully work.

## Expected Behavior

Obtain PR statistics for any repo, regardless if it has a lot of PRs or none.  In my use case of 2 open PRs and none closed/merged, I'd assume the average time to close should still be able to be calculated, but the merged to closed ratio instead of being NaN% should default to 0%.

## Current Behavior

On a new repo I have, the homepage widget is broken.  I tested with no PRs, one, and two, and the maths just expects that I've merged at least one. But it seems to be dividing by zero, thus resulting in NaN.

![image](https://user-images.githubusercontent.com/33203301/98273686-83978980-1f60-11eb-9249-0172ff854f91.png)

![image](https://user-images.githubusercontent.com/33203301/98273729-927e3c00-1f60-11eb-94a1-144b44ec9103.png)

![image](https://user-images.githubusercontent.com/33203301/98273783-a3c74880-1f60-11eb-9e0e-bdf99aefcfe9.png)

## Possible Solution

* Average time when no PRs have ever been merged in a repo could be "Never".
* For ratio, a check if the divisor is zero should default to the display just being 0%.

## Steps to Reproduce

1. Create an empty repo
2. Add a catalog yaml
3. Onboard to backstage
4. View the stats panel

## Context

Likely should get some test cases in there where the number results back from the GitHub API would have the varying numbers 0 open, 0 closed / 5 open, 0 closed / 5 open, 15 closed, that sort of thing.

## Your Environment

- Plugin Version (version of this software e.g. v0.4.3): 0.6.1
- Backstage version (e.g. 0.1.1-alpha23): 0.2.0
- NodeJS Version (e.g. v12): 12.16.2
- Operating System and Version (e.g. Ubuntu 14.04): Windows 10 1909, WSL2, Ubuntu 18.04
- Browser Information (e.g. chrome 85): Microsoft Edge (Chrome engine 86)

**Comment by dtuite** [comment]
Thanks @adamdmharvey. We'll look into this.
