### ISSUE TITLE
Add pull request status (open/closed) to PR table

### ISSUE THREAD

**Issue by adamdmharvey** [RoadieHQ/backstage-plugin-github-pull-requests#27]
## Feature Suggestion

On the pull request table, there are three very nice filter buttons to show open, closed, or all pull requests.  However, when you pick the "all", you can't actually tell which category the PRs fall into.

![image](https://user-images.githubusercontent.com/33203301/98276402-e8081800-1f63-11eb-8f15-0d4e921a1fbb.png)

## Possible Implementation

As an equivalent to the GitHub interface, when viewing all PRs without looking at status, the icon indicates the PR is either green or purple:

![image](https://user-images.githubusercontent.com/33203301/98276279-bc852d80-1f63-11eb-8670-5f657c8aff2e.png)

Suggest showing an icon according to the status would be great, but even just a simple column with the status could be useful as well.

**Comment by dtuite** [comment]
Love it @adamdmharvey

**Comment by adamdmharvey** [comment]
I updated to 0.6.2 and it looks great, thanks!

![image](https://user-images.githubusercontent.com/33203301/98579482-b73e2080-228c-11eb-8a38-e09be9583881.png)
