### ISSUE TITLE
GitHub authentication based on access token / github application

### ISSUE THREAD

**Issue by omerlh** [RoadieHQ/backstage-plugin-github-pull-requests#33]
## Feature Suggestion

Right now, this plugin is depend on GitHub authentication, which is not something I am planning on using.
I would like this plugin to use the GitHub integration credentials (PAT for example) instead of relaying on the auth method.

**Comment by dtuite** [comment]
Hey @omerlh. Good to see you around! 😀

Firstly, we totally agree that it would be nice to be able to run the plugin through a backend PAT. 

When we created this plugin, we followed an established pattern which exists in Backstage and is used for all other GitHub interactions, such as the GitHub Actions plugin (which was created by the Backstage team). If there was another standard pattern available for using a backend PAT then we would use that instead.

Would you mind generalising this GitHub issue please and opening it against backstage/backstage instead? It should be something like "GitHub plugins should have the option of using a PAT stored in the backend".

**Comment by omerlh** [comment]
Sure, here it is - appreciate if you could chime in: backstage/backstage#3586
