### ISSUE TITLE
npm registry does not have latest release 0.6.5 (or 0.6.6)

### ISSUE THREAD

**Issue by fidelcoria-aa** [RoadieHQ/backstage-plugin-github-pull-requests#58]
## Expected Behavior

I should be able to download version 0.6.5 from npm registry

## Current Behavior

only version 0.6.4 available.

## Context

I'm getting warning about duplicate packages and outdated dependencies. 

## Your Environment

- Plugin Version (version of this software e.g. v0.4.3): 0.6.4
- Backstage version (e.g. 0.1.1-alpha23): latest release
- NodeJS Version (e.g. v12): 12
- Operating System and Version (e.g. Ubuntu 14.04): win 10
- Browser Information (e.g. chrome 85): chrome

**Comment by padraigobrien** [comment]
Hi, I will have a look into this for you

**Comment by dtuite** [comment]
@fidelcoria-aa Thank you for flagging this. You should see that `0.6.8` has been published [to npm](https://www.npmjs.com/package/@roadiehq/backstage-plugin-github-pull-requests).

We will take a look through the rest of our plugins now.
