### ISSUE TITLE
Is there any plan of adding a Widget to this?

### ISSUE THREAD

**Issue by ebarriosjr** [RoadieHQ/backstage-plugin-github-pull-requests#7]
Hi, i was wondering if there is any plan to add a Widget to this plugin to be able to integrate it into the backstage catalog plugin.

I want to have it as an tab inside the catalog view.

Thanks!

**Comment by iain-b** [comment]
Hi @ebarriosjr, yes we plan to facilitate that but were waiting for https://github.com/spotify/backstage/pull/2076 to be merged upstream first as we'll be building on that approach.

**Comment by ebarriosjr** [comment]
I did the widget locally and it works great, but the pr is already merged so i guess you guys were smarter than me on waiting :P Thanks for the response.
