### ISSUE TITLE
Error: No ApiProvider available in react context

### ISSUE THREAD

**Issue by athal7** [RoadieHQ/backstage-plugin-github-pull-requests#73]
## Expected Behavior

Page renders

## Current Behavior

Page not rendering, with the console error: `Error: No ApiProvider available in react context`

## Possible Solution\

n/a

## Steps to Reproduce

1. Follow the instructions in the README
2. visit `component/x/pull-requests`

## Your Environment

- Plugin Version (version of this software e.g. v0.4.3): v0.7.6
- Backstage version (e.g. 0.1.1-alpha23): 0.6.0
- NodeJS Version (e.g. v12): v14
- Operating System and Version (e.g. Ubuntu 14.04): Docker node:14-buster
- Browser Information (e.g. chrome 85): chrome 88

**Comment by padraigobrien** [comment]
Hey @athal7 , this looks similar to the other issue you are having, I will look at this also

**Comment by athal7** [comment]
I’ll go ahead and re-verify it after the release of the buildkite package

**Comment by padraigobrien** [comment]
Hey @athal7 I will update this package now

**Comment by padraigobrien** [comment]
This work has been completed and npm has been updated, https://www.npmjs.com/package/@roadiehq/backstage-plugin-github-pull-requests. i will close but if there are any other issues dont hesitate to reach out
