### ISSUE TITLE
Release latest changes which updates backstage dependencies

### ISSUE THREAD

**Issue by pjagadeesan** [RoadieHQ/backstage-plugin-github-pull-requests#81]
## Context

We are trying to override the Support Button config to point to custom slack channel rather than backstage. 
This feature is available in the latest version of @backstage/core@0.7.2

This change has already been made in your repo but not been released yet.

**Comment by dtuite** [comment]
Hi @pjagadeesan. Apologies for the delay. We have hired someone to work full time on plugin development. They will start soon and we should develop a better release cadence once they get up to speed.

We will try to get this release out as soon as possible.

**Comment by Xantier** [comment]
Hello @pjagadeesan. We have now released a new version of the plugin with updated dependencies. It should be available with version `0.7.9`. I'm closing this issue, let me know if there is anything else related to this.

**Comment by pjagadeesan** [comment]
Thank you for working on this quickly!
